/**
 * Signal Model - Stores trading signals generated by strategy
 */

const mongoose = require('mongoose');

const signalSchema = new mongoose.Schema({
  symbol: {
    type: String,
    required: true,
    index: true,
  },
  timestamp: {
    type: Date,
    required: true,
    index: true,
  },
  type: {
    type: String,
    required: true,
    enum: ['CALL', 'PUT'],
  },
  entry: {
    type: Number,
    required: true,
  },
  stopLoss: {
    type: Number,
    required: true,
  },
  target: {
    type: Number,
    required: true,
  },
  riskReward: Number,
  strikes: mongoose.Schema.Types.Mixed,
  analysis: {
    cpr: mongoose.Schema.Types.Mixed,
    supportResistance: mongoose.Schema.Types.Mixed,
    bias: String,
    decision: mongoose.Schema.Types.Mixed,
    strikeSelection: mongoose.Schema.Types.Mixed,
    optionTrade: mongoose.Schema.Types.Mixed,
    narrowCPR: Boolean,
    cprWidthType: String,
    amZone: mongoose.Schema.Types.Mixed,
    manipulation: mongoose.Schema.Types.Mixed,
    strongCandle: Boolean,
    volumeSpike: Boolean,
    mtfConfirmed: Boolean,
    atr: Number,
    marketContext: mongoose.Schema.Types.Mixed,
    levels: mongoose.Schema.Types.Mixed,
    camarilla: mongoose.Schema.Types.Mixed,
    roundNumbers: mongoose.Schema.Types.Mixed,
    confluence: mongoose.Schema.Types.Mixed,
    liquidity: mongoose.Schema.Types.Mixed,
    marketPhase: mongoose.Schema.Types.Mixed,
    events: [String],
    passiveMetrics: mongoose.Schema.Types.Mixed,
    previousDay: mongoose.Schema.Types.Mixed,
  },
  scoring: {
    score: Number,
    grade: String,
    tradeable: Boolean,
    confidence: String,
  },
  status: {
    type: String,
    enum: ['GENERATED', 'EXECUTED', 'IGNORED'],
    default: 'GENERATED',
  },
  executedTradeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trade',
  }
}, {
  timestamps: true,
  collection: 'signals'
});

signalSchema.index({ symbol: 1, timestamp: -1 });
signalSchema.index({ status: 1, timestamp: -1 });

module.exports = mongoose.model('Signal', signalSchema);
