/**
 * Signal Model - Stores trading signals generated by strategy
 */

const mongoose = require('mongoose');

const signalSchema = new mongoose.Schema({
  symbol: {
    type: String,
    required: true,
    index: true,
  },
  timestamp: {
    type: Date,
    required: true,
    index: true,
  },
  type: {
    type: String,
    required: true,
    enum: ['CALL', 'PUT'],
  },
  entry: {
    type: Number,
    required: true,
  },
  stopLoss: {
    type: Number,
    required: true,
  },
  target: {
    type: Number,
    required: true,
  },
  riskReward: Number,
  strikes: {
    atm: String,
    itm1: String,
    itm2: String,
    otm1: String,
    otm2: String,
  },
  analysis: {
    cpr: mongoose.Schema.Types.Mixed,
    supportResistance: mongoose.Schema.Types.Mixed,
    bias: String,
    narrowCPR: Boolean,
    cprWidthType: String,
    amZone: mongoose.Schema.Types.Mixed,
    manipulation: mongoose.Schema.Types.Mixed,
    strongCandle: Boolean,
    volumeSpike: Boolean,
    mtfConfirmed: Boolean,
    atr: Number,
  },
  scoring: {
    score: Number,
    grade: String,
    tradeable: Boolean,
    confidence: String,
  },
  status: {
    type: String,
    enum: ['GENERATED', 'EXECUTED', 'IGNORED'],
    default: 'GENERATED',
  },
  executedTradeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trade',
  }
}, {
  timestamps: true,
  collection: 'signals'
});

signalSchema.index({ symbol: 1, timestamp: -1 });
signalSchema.index({ status: 1, timestamp: -1 });

module.exports = mongoose.model('Signal', signalSchema);
